### ISSUE TITLE
Internet Browser Freezes [BUG]

### ISSUE THREAD

**Issue by HugaShire** [Maschell/hid_to_vpad#26]
When HID to VPAD is running, and you try launching the Internet Browser, It will freeze

**Comment by CreeperMario** [comment]
What about other "background" programs, such as Miiverse, eShop or Download Management? Do they crash too?

**Comment by omardlr** [comment]
i have this problem too, 
Wii U Black, Ver. 5.5.1
HIDtoVPAD v0.9j

**Comment by Maschell** [comment]
Fixed with commit f7ccd7d

**Comment by jack4455667788** [comment]
@Maschell - I am experiencing this bug in 5.5.2 (5.5.3, but as far as I understand it, kernel and browser are the same as 5.5.2).... I have tried both the latest stable release (.9k) as well as various nightlies of the standard and wups varieties. 

Update - I have determined that this issue is only present when I am in a particular game.  I am unsure as to whether it is due to the game itself (assassins creed black flag) or the fact that the game is installed on USB instead of nand (only game I have like this, no more room on the usb but I'll try with another title when I get a chance) and whether 5.5.2 has any bearing on it at all... 

Reiterating what I said above; I can access the internet browser without issue while HID to VPAD is running (in game or not) as long as the game is installed on the nand (or possibly, just isn't assassins creed black flag)
